# Generated by Django 3.1.6 on 2021-02-06 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='分类名称')),
                ('index', models.IntegerField(default=99, verbose_name='分类排序')),
                ('active', models.BooleanField(default=True, verbose_name='是否添加到菜单')),
                ('icon', models.CharField(default='fa-home', max_length=30, verbose_name='菜单图标')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('url', models.URLField(verbose_name='地址')),
                ('desc', models.TextField(max_length=250, verbose_name='描述')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50, verbose_name='网站描述')),
                ('keywords', models.CharField(max_length=50, verbose_name='网站关键词')),
                ('title', models.CharField(max_length=50, verbose_name='网站标题')),
                ('index_title', models.CharField(max_length=50, verbose_name='首页标题')),
                ('site_mail', models.CharField(max_length=50, verbose_name='我的邮箱')),
                ('site_qq', models.CharField(max_length=50, verbose_name='我的QQ')),
                ('site_avatar', models.CharField(default='https://image.3001.net/images/20171226/15142933784705.png', max_length=200, verbose_name='我的头像')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('desc', models.TextField(max_length=100, verbose_name='文章描述')),
                ('cover', models.CharField(default='https://image.3001.net/images/20200304/15832956271308.jpg', max_length=200, verbose_name='文章封面')),
                ('content', mdeditor.fields.MDTextField(verbose_name='文章内容')),
                ('click_count', models.IntegerField(default=0, verbose_name='点击次数')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myblog.category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
