# Generated by Django 3.1.6 on 2021-02-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='click_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='article',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='article',
            name='update_time',
        ),
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
