# Generated by Django 3.1.6 on 2021-02-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20210206_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
