# Generated by Django 3.1.6 on 2021-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='linkcontent',
        ),
        migrations.AddField(
            model_name='link',
            name='content',
            field=models.TextField(default=1, verbose_name='正文'),
        ),
    ]
