# Generated by Django 3.1.6 on 2021-02-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20210208_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='content',
            field=models.TextField(default='', verbose_name='正文'),
        ),
    ]
