# Generated by Django 3.1.6 on 2021-02-08 15:01

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_auto_20210208_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
